matrix:
  include:
    - language: node_js
      os: linux
      node_js:
        - '11'
      addons:
        chrome: stable
      script:
        # no need for `npm ci`, travis-ci does this automatically
        - npm run lint
        - npm run test:ci
        - npm run build:web:prod
        - npm run build:electron:prod

    # deployment only works on osx
    - language: node_js
      os: osx
      node_js:
        - '11'
      addons:
        chrome: stable
      script:
        # no need for `npm ci`, travis-ci does this automatically
        - npm run lint
        - npm run test:ci
        - npm run build:web:prod
        - npm run build:electron:prod
      deploy:
        - skip_cleanup: true
          provider: script
          script: /bin/bash .travis/deploy.sh
          on:
            tags: true
            repo: borisskert/electron-updater-test

env:
  global:
    # export CSC_LINK=[secure]
    # export BASE64_CSC_KEY_PASSWORD=[secure]
    - secure: "MqYLghFz4v5A+BurlOLsdsHgVN7racE+OFgUaWDNf2pWn93FctCy1czBm6pSToyoIIPSnDPyEwQLrJBiNraTQvAeDD/SE5HGouSuJH3sDFEJrydgbm/RaYvBwXND9JkOPwZY255YTuevPSLG5CUQ4MEblkOKpjr0ImNh/xSw2SoqFYh3mzrtNNEA+hBSIdcnHRgASJOxMTx1rXgf0DzCs+geoTnWUIlrAi6M39THkbCyZfR1nMKnMpg+a1fmiREYo+DEE6dAxFSi2xpfHhr31hEHYVRmLOLCzoR8kLKmHiPsvmmJGLHP7tDsq3pfp4KCc6JOcyo7hEj7zS22QXA34fkTXr8IzOL08b+UbYt0qhC4lG096jL/bkJLywMKZzoBT1asZVl+FnX/oZJ91npirUtPQikYd1A/oL4WVfmBbn6Yd0/O1Pmzq+v8pyG/sWx5uDxVQl6o6Z48n4eyjkeX2/InCCDVem7Fyv0jksQIpwgqcllBfT3IBGa17cFbPVGzLRvhj0s/qdCwoFVZ/flGTXxDQraeVz8lCgwW/sNWKFJiZvVTjWrdTTK26r/bSIGC5xgYfZGLQII1h4dpuhb4kZHJ6K+o/AZ1ZXuP6f/jXTizBbncRgJRroZ2/WlPr5oE3yvw1P1t+RM31vgG20zBuZmgvKsz0cdj3o/E5XpL+90="
    # export GH_TOKEN=[secure]
    - secure: "ZKl9tJOEKpjxR/kiduH5PhSTfaklZb9LTrSvPNKP1ySAR34OI2rllxrJ0ULxLhJ8wWmBbkYZfeLoH3HULSJodWtm9RwjGee9yXX0JuWZLuWdNiaddZLXNvgyUTRrDrrwFs4OmWjljazOZku+AWiCtlC572MH19mzfytvETK++1XMWMqIyVqhrwx12bivs89hRZIawr6vOC2Jpx9pIXrHz2tfOxRiuG9gZoOGseWasBIXsjQmhBXhV85eYntkhsh7+4vlCOiDoMk9CxfCORL1dVAQSxWWtm1rO5jNOz9V059DnnKo3oNvP9A04mlZHUj96OvZmnOLe9n4Numkzb7lOZfygSzlJ9qXjqRZ9ravtuDQL4aVNuVkOWb79Wc7riocdT2QGj0SrBseXssZXb5Ujnj+aLULBaP27r0DDzV6GU0mQu+mQ3xqdLtaoyXi44eqW6SiAcLCPv4pV1jlceyueGEJ1G6O5B2gI8q0yALThc1JxwnBmTnuVcoW7Zynv2lnmgF11A2ErdqKyS7KeYlZVEKfz7ZsyBPA91G5BuZdMb+t3K3SUyGKyqUetT38F3TVRteTZJWJrej3B1TQWB5LPRDUdNgNtSLme6he4cq5LHdbwcpSZKHd+WXWxbKZ5vR8BIgE+j8WebPz9nHp89C7av0j2tdKYRizvCSFGWt1p/8="
