matrix:
  include:
    - language: node_js
      node_js:
        - '11'
      addons:
        chrome: stable
      script:
        - npm ci
        - npm run lint
        - npm run test:ci
        - npm run build:web:prod
    - language: node_js
      os: osx
      node_js:
        - '11'
      addons:
        chrome: stable
      script:
        - ENCRYPTED_CERT_P12=encrypted.cert.p12
        - DECRYPTED_CERT=cert.pem
        - curl -L -o "${ENCRYPTED_CERT_P12}" ${CSC_LINK}
        - export CSC_KEY_PASSWORD=$(echo ${BASE64_CSC_KEY_PASSWORD} | base64 -D)
        - openssl pkcs12 -in "${ENCRYPTED_CERT_P12}" -nodes -out "${DECRYPTED_CERT}" -password pass:${CSC_KEY_PASSWORD}
        - sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "${DECRYPTED_CERT}"
        - npm run electron:mac
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: gz4x+tCnNlh/K//2vQl85Oa6rPehlLtvtqb9lWQ+fC67M/fY8CLoE6IZkTioCVPo6cH/sEtDs8ipW3baXJjo+i+GUPwPDMcCKrdSLvtsvQ8dzrofUXqAgMgKGZ5GytLNWYKpOnhUysOhYOtHk2xvpv05Dl4Tk1hvv8WL88exK9PVHcwMHtjx2XAeELnLQVOs1Oxd+GESuq/u53BM6S/KSAzELdixBc0EKdE+3IG6gaqJ5ObN+I1EKhrNOvWqkuxkNoMORPJTrE5vbJC2yvjf5I8XEPdhtO0FfSNBT3NFj9/Ai73kVZb9PS0cbNaLRb9EiLlWvY444rQ6Jb1EorR5AF6m90NOUkVH9pPoy96xzM9xc9qpLobpQXlA0L6PTVaA+8Uk8XI/pR4VelTfNBi99WgngxcKcBzTk4m/Rp14GBEgrkcrAACzDJ1lqpLToLYC872oNur/KlrYLeKd2668gNMfqb0SAEfvmNIOdoadn0J04EU4DI8b55l8h5RlZNMfeE7Xd8QwOa1kD4d53xteaywr4F7cv6DhuetMnCSa1DXy4HXmpah5bIgIR7TI5SOcaxwosB37kCZlT0YM+KnG2zHqDvZT7fMLcZdAEltrT6hf2R0SeJzaKYut1HgWCc7MY19XgH9oXU9F5ewWs5QDigsgQ2baksCP+XonqZIwRBo=
        file_glob: true
        file: release/ng-electron-*.dmg
        on:
          repo: borisskert/electron-updater-test
          tags: true
    - language: node_js
      os: osx
      node_js:
        - '11'
      addons:
        chrome: stable
      script:
        - ENCRYPTED_CERT_P12=encrypted.cert.p12
        - DECRYPTED_CERT=cert.pem
        - curl -L -o "${ENCRYPTED_CERT_P12}" ${CSC_LINK}
        - export CSC_KEY_PASSWORD=$(echo ${BASE64_CSC_KEY_PASSWORD} | base64 -D)
        - openssl pkcs12 -in "${ENCRYPTED_CERT_P12}" -nodes -out "${DECRYPTED_CERT}" -password pass:${CSC_KEY_PASSWORD}
        - sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "${DECRYPTED_CERT}"
        - npm run electron:windows
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: gz4x+tCnNlh/K//2vQl85Oa6rPehlLtvtqb9lWQ+fC67M/fY8CLoE6IZkTioCVPo6cH/sEtDs8ipW3baXJjo+i+GUPwPDMcCKrdSLvtsvQ8dzrofUXqAgMgKGZ5GytLNWYKpOnhUysOhYOtHk2xvpv05Dl4Tk1hvv8WL88exK9PVHcwMHtjx2XAeELnLQVOs1Oxd+GESuq/u53BM6S/KSAzELdixBc0EKdE+3IG6gaqJ5ObN+I1EKhrNOvWqkuxkNoMORPJTrE5vbJC2yvjf5I8XEPdhtO0FfSNBT3NFj9/Ai73kVZb9PS0cbNaLRb9EiLlWvY444rQ6Jb1EorR5AF6m90NOUkVH9pPoy96xzM9xc9qpLobpQXlA0L6PTVaA+8Uk8XI/pR4VelTfNBi99WgngxcKcBzTk4m/Rp14GBEgrkcrAACzDJ1lqpLToLYC872oNur/KlrYLeKd2668gNMfqb0SAEfvmNIOdoadn0J04EU4DI8b55l8h5RlZNMfeE7Xd8QwOa1kD4d53xteaywr4F7cv6DhuetMnCSa1DXy4HXmpah5bIgIR7TI5SOcaxwosB37kCZlT0YM+KnG2zHqDvZT7fMLcZdAEltrT6hf2R0SeJzaKYut1HgWCc7MY19XgH9oXU9F5ewWs5QDigsgQ2baksCP+XonqZIwRBo=
        file_glob: true
        file: release/ng-electron *.exe
        on:
          repo: borisskert/electron-updater-test
          tags: true

env:
  global:
    # encrypted CSC settings
    - secure: "MqYLghFz4v5A+BurlOLsdsHgVN7racE+OFgUaWDNf2pWn93FctCy1czBm6pSToyoIIPSnDPyEwQLrJBiNraTQvAeDD/SE5HGouSuJH3sDFEJrydgbm/RaYvBwXND9JkOPwZY255YTuevPSLG5CUQ4MEblkOKpjr0ImNh/xSw2SoqFYh3mzrtNNEA+hBSIdcnHRgASJOxMTx1rXgf0DzCs+geoTnWUIlrAi6M39THkbCyZfR1nMKnMpg+a1fmiREYo+DEE6dAxFSi2xpfHhr31hEHYVRmLOLCzoR8kLKmHiPsvmmJGLHP7tDsq3pfp4KCc6JOcyo7hEj7zS22QXA34fkTXr8IzOL08b+UbYt0qhC4lG096jL/bkJLywMKZzoBT1asZVl+FnX/oZJ91npirUtPQikYd1A/oL4WVfmBbn6Yd0/O1Pmzq+v8pyG/sWx5uDxVQl6o6Z48n4eyjkeX2/InCCDVem7Fyv0jksQIpwgqcllBfT3IBGa17cFbPVGzLRvhj0s/qdCwoFVZ/flGTXxDQraeVz8lCgwW/sNWKFJiZvVTjWrdTTK26r/bSIGC5xgYfZGLQII1h4dpuhb4kZHJ6K+o/AZ1ZXuP6f/jXTizBbncRgJRroZ2/WlPr5oE3yvw1P1t+RM31vgG20zBuZmgvKsz0cdj3o/E5XpL+90="
    # encrypted electron-builder settings
    - secure: "ZKl9tJOEKpjxR/kiduH5PhSTfaklZb9LTrSvPNKP1ySAR34OI2rllxrJ0ULxLhJ8wWmBbkYZfeLoH3HULSJodWtm9RwjGee9yXX0JuWZLuWdNiaddZLXNvgyUTRrDrrwFs4OmWjljazOZku+AWiCtlC572MH19mzfytvETK++1XMWMqIyVqhrwx12bivs89hRZIawr6vOC2Jpx9pIXrHz2tfOxRiuG9gZoOGseWasBIXsjQmhBXhV85eYntkhsh7+4vlCOiDoMk9CxfCORL1dVAQSxWWtm1rO5jNOz9V059DnnKo3oNvP9A04mlZHUj96OvZmnOLe9n4Numkzb7lOZfygSzlJ9qXjqRZ9ravtuDQL4aVNuVkOWb79Wc7riocdT2QGj0SrBseXssZXb5Ujnj+aLULBaP27r0DDzV6GU0mQu+mQ3xqdLtaoyXi44eqW6SiAcLCPv4pV1jlceyueGEJ1G6O5B2gI8q0yALThc1JxwnBmTnuVcoW7Zynv2lnmgF11A2ErdqKyS7KeYlZVEKfz7ZsyBPA91G5BuZdMb+t3K3SUyGKyqUetT38F3TVRteTZJWJrej3B1TQWB5LPRDUdNgNtSLme6he4cq5LHdbwcpSZKHd+WXWxbKZ5vR8BIgE+j8WebPz9nHp89C7av0j2tdKYRizvCSFGWt1p/8="
